version: '3.7'

services:

  app:
    container_name: blackjack-assistant_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: grigarzi/blackjack-frontend
    ports:
      - '1337:80'