version: '3.7'

services:

  app:
    image: grigarzi/blackjack-frontend
    labels:
      - "traefik.http.routers.app.rule=PathPrefix(`/`)"
      #- "traefik.http.services.app.loadbalancer.server.port=1337"
  api:
    restart: on-failure
    command: python blackjack_backend/manage.py runserver 0.0.0.0:8000
    image: grigarzi/blackjack-backend
    labels:
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    # Enables the web UI and tells Traefik to listen to docker
    command: --providers.docker
    ports:
      # The HTTP port
      - "80:80"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    