version: '3.7'

services:

  app_dev:
    container_name: blackjack-assistant_dev
    build:
      context: .
      dockerfile: Dockerfile
    image: grigarzi/blackjack-frontend_dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true